general {
    immediate_render = true
    hide_cursor = true
}

# Фон с обоями и блюром
background {
    monitor =
    path = /home/haunt/.config/hypr/wallpapers/kali-tiles.jpg
    blur_passes = 2
    blur_size = 5
}

# Поле ввода пароля
input-field {
    monitor =

    size = 320, 60
    position = 0, -40
    halign = center
    valign = center

    border_size = 2
    border_color = rgba(3c6eb4ee) rgba(1a4d8cee) 45deg
    background_color = #1e1e1e
    rounding = 0

    placeholder_text = Пароль
    placeholder_color = #7f849c
    fail_text = Неверный пароль
    fail_color = #f38ba8

    fade_on_empty = false
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    hide_input = false
}
