# Шрифт как в Kali
font_family      Hack Nerd Font
font_size        10

# Прозрачность и блюр
background_opacity 0.6
# Цветовая схема (Kali-вайб)
background #1e1e1e
foreground #d3dae3
selection_background #3c6eb4

# Отключаем рамки окон (для Hyprland)
hide_window_decorations titlebar-only

# Удобные бинды
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# Скроллбек и производительность
scrollback_lines 5000
cursor_trail 3
